name: GitHub-Profile-Summary-Cards

on:
  schedule: # Dawasata eka paarak update wenawa
    - cron: "0 0 * * *"
  workflow_dispatch: # Kamathi welawaka button eka obala run karanna puluwan

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # Podi mathak kirimak: Oyage repo settings wala thiyena secret eke nama 'GH_TOKEN' kiyala waga thahawuru karaganna.
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # Oya select karapu 'dark' theme eka methana thiyenawa
          THEME: dark
